### ISSUE TITLE
EasyMark for PHP 5.3 and Typesetter ver. 5

### ISSUE THREAD

**Issue by juek** [ppeterka/easymark#2]
Hi Peter, 
just in case you're not following the plugin forum, please read:
[EasyMark Support Forum](http://www.typesettercms.com/Forum?show=t2104)

**Comment by ppeterka** [comment]
Hi Juergen,

Thanks, I'll take a look at it - been quite busy lately, didn't have time
for it...

Best Regards,
Peter

**Comment by ppeterka** [comment]
Hello Jürgen,

I went through the differences... Thanks for your changes, they all make
perfect sense, and very nicely coded. I'm not really up to date in the
delicacies of different PHP versions...

To make things complete, I'd like to upload the changes to github too - and
to be sure, I'd like to ask your permission to do so... I also added an
"acknowledgements" section to the admin page, I'd like to put a link to
your github page there, is it OK with you?

Thanks again,
Peter

**Comment by juek** [comment]
> I'm not really up to date in the delicacies of different
> PHP versions...

So am I :) It's just the Error->Google->StackOverflow(.com)->Fix route i
went.

> To make things complete, I'd like to upload the changes to github
> too - and to be sure, I'd like to ask your permission to do so...
> I also added an "acknowledgements" section to the admin page,
> I'd like to put a link to your github page there, is it OK with you?

OMG, sure! And there is no need for any attribution.
Up to now my github page is nothing more than a container for temporary
pull requests. My coding practices are far too chaotic for public
repositories :-]

And BTW thanks for the cool plugin! It was high time for Markdown
support in gpEasy/Typesetter!

**Comment by ppeterka** [comment]
Hello Jürgen,

Done - released 1.3.1, so if all is well, it should be downloadable for
everyone (http://www.typesettercms.com/Plugins/301_EasyMark_MarkDown_for_GPEasy).

Actually when I created the plugin, I was deeply surprised nobody did it
before me - I'm usually late to the party when it comes to such... I was
sure that it was something that could improve the brilliant little CMS that
GPEasy/Typesetter is. It sure feels good to get positive feedback and see
that it is actually being used - and not only by me.

Thanks again for your contribution!
Peter
